$background = rgb(59422d)
$foreground = rgb(ffdcbf)
$color0 = rgb(fdb975)
$color1 = rgb(4a2800)
$color2 = rgb(865319)
$color3 = rgb(6a3c01)
$color4 = rgb(e1c1a4)
$color5 = rgb(402c18)
$color6 = rgb(59422d)
$color7 = rgb(ffdcbf)
$color8 = rgb(c0cc9a)
$color9 = rgb(2b340f)
$color10 = rgb(414b24)
$color11 = rgb(dce8b4)
$color12 = rgb(ffb4ab)
$color13 = rgb(690005)
$color14 = rgb(93000a)
$color15 = rgb(ffdad6)
