
###############
## AUTOSTART ##
###############
# Wiki: https://wiki.hyprland.org/Configuring/Keywords/#executing

exec-once = hyprpm reload -n &
exec-once = flatpak run me.timschneeberger.jdsp4linux -t &

# Deamons
exec-once = pypr &
exec-once = swww-daemon --format xrgb

