##############
## BINDINGS ##
##############
# Wiki: https://wiki.hyprland.org/Configuring/Binds

bind = $mainMod SHIFT CTRL, 1, exec, astal volume source-mute || wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

bind = CTRL, escape, exec, flatpak run net.nokyan.Resources/x86_64/stable

# Uncomment if you want to press SUPER to launch application search
# bind = $mainMod, $mainMod_L, exec, astal toggle apps-window
