############
## LAYOUT ##
############
# Wiki: https://wiki.hyprland.org/Configuring/Dwindle-Layout/#config

dwindle {
  pseudotile = yes
  preserve_split = yes
  special_scale_factor = 0.8
}

master {
  new_status = master #from Hyprland >v0.41.2
  new_on_top = 1
  mfact = 0.5
}
