
############################
##  WINDOW & LAYER RULES  ##
############################

# See https://wiki.hyprland.org/Configuring/Window-Rules for
# more information on how to do this

binds {
  workspace_back_and_forth = true
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
}
