
###############
## AUTOSTART ##
###############

# Services/Daemons
exec-once = systemctl enable --user --now hyprpolkitagent.service
exec-once = mako
exec-once = eww daemon --no-daemonize
exec-once = hypridle
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Tools
exec-once = hyprpaper

# Scripts
exec-once = sh $HOME/.config/hypr/scripts/gen-pywal.sh
exec-once = sh $HOME/.config/hypr/scripts/night-light-check.sh
exec-once = sh $HOME/.config/hypr/scripts/notification-handler-daemon.sh

# Widgets
exec-once = sh "$(eww get EWW_CONFIG_DIR)/scripts/eww-window.sh" open bar


# Apps 
exec-once = /bin/vesktop --start-minimized
exec-once = /bin/steam-runtime -silent
