
#############################################
## Retrozinndev's Hyprland Configurations! ##
#############################################

# From https://github.com/retrozinndev/Hyprland-Dots
# Made with lots of love 󰋑 , by retrozinndev 
# Licensed under the MIT License

# Nvidia Settings
source = ~/.config/hypr/nvidia.conf

# Environment
source = ~/.config/hypr/environment.conf

# Monitors
source = ~/.config/hypr/monitors.conf

# Layout
source = ~/.config/hypr/layout.conf

# Input
source = ~/.config/hypr/input.conf

# Appearance
source = ~/.config/hypr/decorations.conf

# Rules
source = ~/.config/hypr/rules.conf

# Bindings
source = ~/.config/hypr/bindings.conf

# Autostart
source = ~/.config/hypr/autostart.conf
