
# color-shell specific configuration, please don't modify unless you know what you're doing!

# Daemons
# exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 # GNOME PolKit
exec-once = systemctl enable --user --now hyprpolkitagent # Hyprland's PolKit
exec-once = systemctl enable --user --now hypridle
exec-once = systemctl enable --user --now gnome-keyring-daemon
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Tools
exec-once = systemctl enable --user --now hyprpaper
exec-once = systemctl enable --user --now hyprsunset

# Scripts
exec-once = sh ../scripts/gen-pywal.sh
exec-once = sh ../scripts/night-light-check.sh

# Other
exec-once = ags run
