
source = ./variables.conf
source = ./nvidia.conf
source = ./environment.conf
source = ./bindings.conf
source = ./decorations.conf
source = ./autostart.conf
source = ./rules.conf
source = ./layout.conf
