$background = rgb(5c3f41)
$background_rgb = 92, 63, 65
$foreground = rgb(ffdadb)
$primary = rgb(ffb2b7)
$primary_fixed = rgb(ffdadb)
$primary_fixed_dim = rgb(ffb2b7)
$on_primary = rgb(561d24)
$on_primary_container = rgb(ffdadb)
$inverse_primary = rgb(8f4a50)
$primary_container = rgb(723339)
$secondary = rgb(e6bdbe)
$on_secondary = rgb(44292b)
$secondary_container = rgb(5c3f41)
$secondary_fixed = rgb(ffdadb)
$tertiary = rgb(e7c08e)
$on_tertiary = rgb(432c06)
$tertiary_container = rgb(5c421a)
$tertiary_fixed = rgb(ffddb3)
$error = rgb(ffb4ab)
$on_error = rgb(690005)
$error_container = rgb(93000a)
$on_error_container = rgb(ffdad6)
