font_family     Fira Code SemiBold
font_size 		16.0
bold_font	auto
italic_font      auto
bold_italic_font auto

background_opacity 0.7
confirm_os_window_close 0

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

selection_foreground none
selection_background none

foreground         {{ colors.on_secondary_container.default.hex }}
background         {{ colors.secondary_container.default.hex }}
cursor             {{ colors.secondary_fixed.default.hex }}

active_tab_foreground     {{ colors.secondary_container.default.hex }}
active_tab_background     {{ colors.on_secondary_container.default.hex }}
inactive_tab_foreground   {{ colors.on_secondary_container.default.hex }}
inactive_tab_background   {{ colors.secondary_container.default.hex }}

active_border_color   {{ colors.secondary_fixed.default.hex }}
inactive_border_color {{ colors.on_secondary_container.default.hex }}
bell_border_color     {{ colors.on_primary.default.hex }}

color0  {{ colors.on_primary.default.hex }}
color1  {{ colors.on_primary_container.default.hex }}
color2  {{ colors.inverse_primary.default.hex }}
color3  {{ colors.primary_fixed.default.hex }}
color4  {{ colors.on_secondary.default.hex }}
color5  {{ colors.on_secondary_container.default.hex }}
color6  {{ colors.secondary_fixed.default.hex }}
color7  {{ colors.secondary_fixed_dim.default.hex }}
color8  {{ colors.on_tertiary.default.hex }}
color9  {{ colors.on_tertiary_container.default.hex }}
color10  {{ colors.tertiary_fixed.default.hex }}
color11  {{ colors.tertiary_fixed_dim.default.hex }}
color12  {{ colors.on_error.default.hex }}
color13  {{ colors.on_error_container.default.hex }}
color14  {{ colors.error_container.default.hex }}
color15  {{ colors.on_error_container.default.hex }}
