$background = rgb({{ colors.secondary_container.default.hex_stripped }})
$background_rgb = {{ colors.secondary_container.default.red | set_lightness: 20.0 }}, {{ colors.secondary_container.default.green | set_lightness: 20.0 }}, {{ colors.secondary_container.default.blue | set_lightness: 20.0 }}
$foreground = rgb({{ colors.on_secondary_container.default.hex_stripped }})
$primary = rgb({{ colors.primary.default.hex_stripped }})
$primary_fixed = rgb({{ colors.primary_fixed.default.hex_stripped }})
$primary_fixed_dim = rgb({{ colors.primary_fixed_dim.default.hex_stripped }})
$on_primary = rgb({{ colors.on_primary.default.hex_stripped }})
$on_primary_container = rgb({{ colors.on_primary_container.default.hex_stripped }})
$inverse_primary = rgb({{ colors.inverse_primary.default.hex_stripped }})
$primary_container = rgb({{ colors.primary_container.default.hex_stripped }})
$secondary = rgb({{ colors.secondary.default.hex_stripped }})
$on_secondary = rgb({{ colors.on_secondary.default.hex_stripped }})
$secondary_container = rgb({{ colors.secondary_container.default.hex_stripped }})
$secondary_fixed = rgb({{ colors.secondary_fixed.default.hex_stripped }})
$tertiary = rgb({{ colors.tertiary.default.hex_stripped }})
$on_tertiary = rgb({{ colors.on_tertiary.default.hex_stripped }})
$tertiary_container = rgb({{ colors.tertiary_container.default.hex_stripped }})
$tertiary_fixed = rgb({{ colors.tertiary_fixed.default.hex_stripped }})
$error = rgb({{ colors.error.default.hex_stripped }})
$on_error = rgb({{ colors.on_error.default.hex_stripped }})
$error_container = rgb({{ colors.error_container.default.hex_stripped }})
$on_error_container = rgb({{ colors.on_error_container.default.hex_stripped }})
