import { AstalIO, execAsync, Gio, GLib, GObject, monitorFile, property, register, timeout } from "astal";

export { Wallpaper };


@register({ GTypeName: "Wallpaper" })
class Wallpaper extends GObject.Object {
    private static instance: Wallpaper;
    #wallpaper: (string|undefined);
    #wallpapersPath: string;

    @property(String)
    public get wallpaper(): (string|undefined) { return this.#wallpaper; }
    public set wallpaper(newValue: string) { this.setWallpaper(newValue); }

    public get wallpapersPath() { return this.#wallpapersPath; }

    constructor() {
        super();

        this.#wallpapersPath = GLib.getenv("WALLPAPERS") ?? `${GLib.get_home_dir()}/wallpapers`;
        //this.#hyprpaperFile = Gio.File.new_for_path(`${GLib.get_user_config_dir()}/hypr/hyprpaper.conf`);
        //this.#swwwOptions = "--transition-fps 165 --transition-type any --transition-duration 2";
        //this.#swwwQuery = await execAsync("sh -c 'swww query | grep -oP 'currently displaying: image: \K.*''"); // Promise? Но мне нужно получить путь из этой команды
        //console.log("Query:", this.#swwwQuery); // Promise?
        this.getWallpaper().then((wall) => {
            if(wall) this.#wallpaper = wall; //if(wall?.trim()) this.#wallpaper = wall.trim();
        });

        let tmeout: (AstalIO.Time|undefined) = undefined;

        

        /*this.#monitor = monitorFile(this.#hyprpaperFile.get_path()!, (_, event) => {
            if(event !== Gio.FileMonitorEvent.CHANGED && event !== Gio.FileMonitorEvent.CREATED &&
              event !== Gio.FileMonitorEvent.MOVED_IN)
                return;

            if(tmeout) return;
            else tmeout = timeout(1500, () => tmeout = undefined);
            
            if(this.#ignoreWatch) {
                this.#ignoreWatch = false;
                return;
            }

            const [ loaded, text ] = this.#hyprpaperFile.load_contents(null);
            if(!loaded) 
                console.error("Wallpaper: Couldn't read changes inside the hyprpaper file!");

            const content = new TextDecoder().decode(text);

            if(content) {
                let setWall: boolean = true;

                for(const line of content.split('\n')) {
                    if(line.trim().startsWith('#'))
                        continue;

                    const lineSplit = line.split('=');
                    const key = lineSplit[0].trim(),
                        value = lineSplit.filter((_, i) => i !== 0).join('=').trim();

                    switch(key) {
                        case "splash": 
                            this.splash = /(yes|true|on|enable|enabled)/.test(value) ? true : false;
                            break;

                        case "wallpaper":
                            if(this.#wallpaper !== value && setWall) {
                                this.setWallpaper(value, false);
                                setWall = false; // wallpaper already set
                            }

                            break;
                    }
                }
            }
        }); */
    }

    /* vfunc_dispose(): void {
        this.#monitor.cancel();
    } */

    /*private writeChanges(): void {
        this.#ignoreWatch = true; // tell monitor to ignore file replace
        this.#hyprpaperFile.replace_async(null, false,
            Gio.FileCreateFlags.REPLACE_DESTINATION,
            GLib.PRIORITY_DEFAULT, null, (_, result) => {
                const res = this.#hyprpaperFile.replace_finish(result);
                if(res) {
                    // success
                    this.#ignoreWatch = true; // tell monitor to ignore this change
                    res.write_bytes_async(new TextEncoder().encode(`# This file was automatically generated by color-shell

                        preload = ${this.#wallpaper}
                        splash = ${this.#splash}
                        wallpaper = , ${this.#wallpaper}`.split('\n').map(str => str.trimStart()).join('\n')),
                        GLib.PRIORITY_DEFAULT, null, (_, asyncRes) => {
                            if(_!.write_finish(asyncRes)) res.flush(null);
                            res.close(null);
                        }
                    );

                    return;
                }

                console.error(`Wallpaper: an error occurred when trying to replace the hyprpaper file`);
            }
        );
    } */

    public static getDefault(): Wallpaper {
        if(!this.instance)
            this.instance = new Wallpaper();
    
        return this.instance;
    }

    public async getWallpaper(): Promise<string|undefined> {
        return await execAsync("sh -c \"swww query | grep -oP 'currently displaying: image: \K.*' \"").then(stdout => { // Проверки на изменения обоев
            const loaded: (string|undefined) = stdout; //.split('=')[1]?.trim()

            if(!loaded) 
                console.warn(`Wallpaper: Couldn't get wallpaper. There is(are) no loaded wallpaper(s)`);

            return loaded;
        }).catch((err: Gio.IOErrorEnum) => {
            console.error(`Wallpaper: Couldn't get wallpaper. Stderr: \n${err.message ? `${err.message} /` : ""} Stack: \n ${err.stack}`);
            return undefined;
        });
    }

    public reloadColors(path: string|Gio.File): void {
        execAsync(`matugen -m dark image "${this.pathReplacer(this.#wallpaper)}"`).then(() => {
            console.log("Wallpaper: reloaded shell colors");
        }).catch(r => {
            console.error(`Wallpaper: Couldn't update shell colors. Stderr: ${r}`);
        });
    }
    public pathReplacer(path: string|undefined): string|undefined {
        if (path) return path.replace(/[\[\]\{\}\(\)\s]/g, '\\$&');
    } 

    public setWallpaper(path: string|Gio.File, write: boolean = true): void {
        execAsync(`swww img ${this.pathReplacer(path)} --transition-fps 165 --transition-type any --transition-duration 2`).then(() => {
            if (this.getWallpaper === path) {
                console.error(`Are you going to change the wallpaper to the same one?`);
                return;
            };
            this.#wallpaper = (typeof path === "string") ? path : path.get_path()!;
            console.log("Wallpaper: ", this.#wallpaper);
            console.log("Replacer: ", this.pathReplacer(path));
            this.reloadColors(path);
            //write && this.writeChanges();
        }).catch(r => {
            console.error(`Wallpaper: Couldn't set wallpaper. Stderr: ${r}`);
        });
        
        /*execAsync(`hyprctl monitors | grep -oP '\d+x\d+@\K[\d.]+' | head -n 1 | awk '{printf("%.0f\n", $1)}'`).then(stdout => {
            execAsync(`swww img ${path} --transition-fps ${stdout} --transition-type any --transition-duration 2`).then(() => {
                this.#wallpaper = (typeof path === "string") ? path : path.get_path()!;
                this.reloadColors();
                write && this.writeChanges();
            }).catch(r => {
                console.error(`Wallpaper: Couldn't set wallpaper. Stderr: ${r}`);
            });
        }).catch((err: Gio.IOErrorEnum) => {
            console.error(`Wallpaper: Couldn't get a monitor's refresh reate. Stderr: \n${err.message ? `${err.message} /` : ""} Stack: \n ${err.stack}`);
        }); */
    }

    public async pickWallpaper(): Promise<string|undefined> {
        return (await execAsync(`zenity --file-selection`).then(wall => {
            if(!wall) return undefined;
            //console.log("Wall: ", wall);
            if (this.getWallpaper === wall) {
                console.error(`Are you going to change the wallpaper to the same one?`);
                return;
            };
            this.setWallpaper(wall);
            return wall;
        }).catch(r => {
            console.error(`Wallpaper: Couldn't pick wallpaper, is \`zenity\` installed? Stderr: ${r}`);
            return undefined;
        }));
    }
}
